### ISSUE TITLE
Plots keep generating at world folder.

### ISSUE THREAD

**Issue by dongmin-dev** [tim03we/FuturePlots#5] opened 2020-05-18 06:11 UTC
No matter how much FuturePlots/worlds you delete world.yml, it occurs again when you restart the server. So regular users can buy Spawn plots that doesn't even exist.

**Comment by tim03we** [comment] 2020-05-18 06:45
Can you explain the problem in more detail so I can fix it?

**Comment by dongmin-dev** [comment] 2020-05-18 06:49
Ok so I'm using latest build of FuturePlots. (From this repo)

When I enter the server, which the basic world is "world", the world.yml keeps creating at the plugins/FuturePlots/worlds so that when I go around at the spawn map, the 'empty plot' hud is showing. And normal users can buy that plot. (which doesn't exist)

**Comment by tim03we** [comment] 2020-05-18 06:53
The world world is a plot world for you, but it was created by you, right?  Which command do you use to claim?

**Comment by dongmin-dev** [comment] 2020-05-18 06:55
> The world world is a plot world for you, but it was created by you, right?  Which command do you use to claim?

No no The 'world' is spawn world which is lobby.
I already made two plot worlds named 'Ground32' and 'Ground64'

The empty plot hud is keep showing at the lobby.

**Comment by tim03we** [comment] 2020-05-18 06:57
Hmm Okay.  Does the plugin have a world.yml?  Normally no files are created automatically.

**Comment by dongmin-dev** [comment] 2020-05-18 06:59
Yes, so I delete them every time when I open/restart the server. It automatically creates world.yml

**Comment by tim03we** [comment] 2020-05-18 07:01
I think I know what it is, but I'm not 100% sure.  Could you send me the level.dat from both worlds or from the world world?

**Comment by tim03we** [comment] 2020-05-18 07:01
So just from the lobbies, where the mistake occurred.

**Comment by tim03we** [comment] 2020-05-18 07:03
If possible also from the plot worlds

**Comment by dongmin-dev** [comment] 2020-05-18 07:06
https://drive.google.com/drive/folders/1-4d2X8OG97PJ111__Ns_7W9C3giuyg4h

**Comment by tim03we** [comment] 2020-05-18 07:14
The suspicion was not confirmed, as I suspected. I wonder how the plugin itself creates files just like that. 🤔

**Comment by tim03we** [comment] 2020-05-18 07:14
The plugin works fine with the worlds here.

**Comment by dongmin-dev** [comment] 2020-05-18 07:15
I tried changing the 'world' name into something else, but same 😥

**Comment by tim03we** [comment] 2020-05-18 07:17
Do other worlds exist?

**Comment by dongmin-dev** [comment] 2020-05-18 07:18
Yes. I have other world named cookie.

**Comment by tim03we** [comment] 2020-05-18 07:19
Okay.  Would it be possible for you to send me the server.log after rebooting, after you have deleted the world.yml

**Comment by dongmin-dev** [comment] 2020-05-18 07:21
You mean Deleting world.yml first and start the server new and send the log?

**Comment by tim03we** [comment] 2020-05-18 07:22
Yeah. Want to take a look at the log, see what the plugin has to say.

**Comment by dongmin-dev** [comment] 2020-05-18 07:33
I'm having little trouble with my pc, I'll let you know when I fix it sorry.

**Comment by tim03we** [comment] 2020-05-18 07:33
Ok

**Comment by dongmin-dev** [comment] 2020-05-18 08:13
I got the reason why world.yml creates.
When a user types /plot info at the lobby, the world.yml creates automatically, and the plots hud appears.

**Comment by tim03we** [comment] 2020-05-18 08:28
Okay I will take a closer look at it and report when the bug is fixed and I have more questions.

**Comment by tim03we** [comment] 2020-05-18 09:40
The bug seems to be fixed now. If there are more problems with this bug, don't hesitate to reopen this issue. The update will be available on NukkitX later this day.

**Closed as completed by tim03we** 2020-05-18 09:40 UTC
